---
title: "compareRadklim"
author: "Felix Simon"
date: "2025-11-20"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r}
source("utils.R")
source("debug_compare_radklim.R")

nc_file <- "../data/daten_ICM/YW_2017.002_20230622.nc"
shp_file <- "../data/daten_ICM/dataset.shp"

res <- compare_radklim_series(
  nc_path = nc_file,
  shp_path = shp_file,
  t_start = "2023-06-22 00:00:00",
  t_end = "2023-06-23 00:00:00"
)
```

# zweiter Vergleich
```{r}
# 5-min-Flächenmax mit HydroStorm-Logik
app_5min <- radklim_app_style(
  nc_path = nc_file,
  shp_path = shp_file,
  t_start = "2023-06-22 00:00:00",
  t_end   = "2023-06-23 00:00:00"
)
# app_5min: datetime, max_mm
colnames(app_5min) <- c("date","max_mm")

# Trusted-Zeitreihe einlesen
trusted <- data.table::fread("../data/daten_ICM/trusted_radklim_series.csv")
trusted[, date := as.POSIXct(date, tz = "UTC")]
setorder(trusted, date)

# Seriös mergen
cmp <- merge(
  app_5min,
  trusted,
  by = "date",
  all = FALSE,
  suffixes = c("_app", "_trusted")
)

cmp[, diff := max_mm - value]

summary(cmp$diff)
head(cmp[abs(diff) > 1e-6])
write.csv(cmp,"../cmp.csv", row.names = FALSE)
```

# dritter Vergleich
```{r}
raw_app <- data.table::fread("../data/hydrostorm_raw_areamax_2025-11-20.csv")
colnames(raw_app) <- c("date","value")
cmp <- merge(raw_app, trusted, by = "date", all=TRUE)
cmp[, diff:= value.x - value.y]
summary(cmp)
cmp[abs(diff) > 1e-6][1:30]

write.csv(cmp,"../cmp2.csv", row.names = FALSE)
```

