---
title: "Analyse Niedeschlag"
author: "Felix Simon"
date: "2025-11-03"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rdwd)
library(scales)
library(data.table)
theme_set(theme_bw())
rm(list = ls())
```


# 1) Stationsdaten
## Waltrop (ID 13696)
```{r}
# Ereignis am 22.06.2023
waltrop062023 <- read_delim("../data/Stationsdaten/produkt_5min_hist_rr_20230601_20230630_13696.txt",
                            delim = ";", escape_double = FALSE, col_types = cols(MESS_DATUM = col_datetime(format = "%Y%m%d%H%M")), trim_ws = TRUE) %>% dplyr::select(MESS_DATUM, RS_05)
waltrop062023 <- waltrop062023 %>% dplyr::filter(MESS_DATUM>=as.POSIXct("2023-06-22 00:00:00", tz="UTC") & 
                                                   MESS_DATUM<=as.POSIXct("2023-06-23 00:00:00", tz="UTC"))

# Ereignis am 04.08.2023
waltrop082023 <- read_delim("../data/Stationsdaten/produkt_5min_hist_rr_20230801_20230831_13696.txt",
                            delim = ";", escape_double = FALSE, col_types = cols(MESS_DATUM = col_datetime(format = "%Y%m%d%H%M")), trim_ws = TRUE) %>% dplyr::select(MESS_DATUM, RS_05)
waltrop082023 <- waltrop082023 %>% dplyr::filter(MESS_DATUM>=as.POSIXct("2023-08-02 00:00:00", tz="UTC") & MESS_DATUM<=as.POSIXct("2023-08-09 00:00:00", tz="UTC"))
```

## Olfen (ID 3795)
```{r}
# Ereignis am 22.06.2023
olfen062023 <- read_delim("../data/Stationsdaten/produkt_5min_hist_rr_20230601_20230630_03795.txt",
                            delim = ";", escape_double = FALSE, col_types = cols(MESS_DATUM = col_datetime(format = "%Y%m%d%H%M")), trim_ws = TRUE) %>% dplyr::select(MESS_DATUM, RS_05)
olfen062023 <- olfen062023 %>% dplyr::filter(MESS_DATUM>=as.POSIXct("2023-06-22 00:00:00", tz="UTC") & 
                                                   MESS_DATUM<=as.POSIXct("2023-06-23 00:00:00", tz="UTC"))

# Ereignis am 04.08.2023
olfen082023 <- read_delim("../data/Stationsdaten/produkt_5min_hist_rr_20230801_20230831_03795.txt",
                            delim = ";", escape_double = FALSE, col_types = cols(MESS_DATUM = col_datetime(format = "%Y%m%d%H%M")), trim_ws = TRUE) %>% dplyr::select(MESS_DATUM, RS_05)
olfen082023 <- olfen082023 %>% dplyr::filter(MESS_DATUM>=as.POSIXct("2023-08-02 00:00:00", tz="UTC") & 
                                                   MESS_DATUM<=as.POSIXct("2023-08-09 00:00:00", tz="UTC"))
```

## Gelsenkirchen-Buer (ID 1595)
```{r}
# Ereignis am 22.06.2023
gelsenkirchen062023 <- read_delim("../data/Stationsdaten/produkt_5min_hist_rr_20230601_20230630_01595.txt",
                            delim = ";", escape_double = FALSE, col_types = cols(MESS_DATUM = col_datetime(format = "%Y%m%d%H%M")), trim_ws = TRUE) %>% dplyr::select(MESS_DATUM, RS_05)
gelsenkirchen062023 <- gelsenkirchen062023 %>% dplyr::filter(MESS_DATUM>=as.POSIXct("2023-06-22 00:00:00", tz="UTC") & 
                                                               MESS_DATUM<=as.POSIXct("2023-06-23 00:00:00", tz="UTC"))

# Ereignis am 04.08.2023
gelsenkirchen082023 <- read_delim("../data/Stationsdaten/produkt_5min_hist_rr_20230801_20230831_01595.txt",
                            delim = ";", escape_double = FALSE, col_types = cols(MESS_DATUM = col_datetime(format = "%Y%m%d%H%M")), trim_ws = TRUE) %>% dplyr::select(MESS_DATUM, RS_05)
gelsenkirchen082023 <- gelsenkirchen082023 %>% dplyr::filter(MESS_DATUM>=as.POSIXct("2023-08-02 00:00:00", tz="UTC") & 
                                                               MESS_DATUM<=as.POSIXct("2023-08-09 00:00:00", tz="UTC"))
```


## Plots
```{r}
# Waltrop 22.06.2023
ggplot(data = waltrop062023, aes(x=MESS_DATUM,y=RS_05)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "5 hours",
                   date_labels = "%d.%m.%y %H:%M") +
  scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/waltrop_raw_062023.png", width = 15, height = 9, units = "cm", dpi = 1200)

# Waltrop 04.08.2023
ggplot(data = waltrop082023, aes(x=MESS_DATUM,y=RS_05)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "1 day",
                   date_labels = "%d.%m.%y") +
  # scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/waltrop_raw_082023.png", width = 15, height = 9, units = "cm", dpi = 1200)

# Olfen 22.06.2023
ggplot(data = olfen062023, aes(x=MESS_DATUM,y=RS_05)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "5 hours",
                   date_labels = "%d.%m.%y %H:%M") +
  scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/olfen_raw_062023.png", width = 15, height = 9, units = "cm", dpi = 1200)

# Olfen 04.08.2023
ggplot(data = olfen082023, aes(x=MESS_DATUM,y=RS_05)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "1 day",
                   date_labels = "%d.%m.%y") +
  # scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/olfen_raw_082023.png", width = 15, height = 9, units = "cm", dpi = 1200)

# Gelsenkirchen 22.06.2023
ggplot(data = gelsenkirchen062023, aes(x=MESS_DATUM,y=RS_05)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "5 hours",
                   date_labels = "%d.%m.%y %H:%M") +
  scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/gelsenkirchen_raw_062023.png", width = 15, height = 9, units = "cm", dpi = 1200)

# Gelsenkirchen 04.08.2023
ggplot(data = gelsenkirchen082023, aes(x=MESS_DATUM,y=RS_05)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "1 day",
                   date_labels = "%d.%m.%y") +
  # scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/gelsenkirchen_raw_082023.png", width = 15, height = 9, units = "cm", dpi = 1200)
```

# 2) RADKLIM
```{r}
# mit netcdf
listUntar <- list.files("../data/RADKLIM/", full.names = TRUE, pattern = ".tar.gz")
untar(listUntar[1], exdir = "../data/RADKLIM/untar/")
unlink(listUntar)

listFiles06 <- list.files(path = "../data/RADKLIM/untar/2023/06", full.names = TRUE, recursive = TRUE, pattern = ".nc")
listFiles08 <- list.files(path = "../data/RADKLIM/untar/2023/08", full.names = TRUE, recursive = TRUE, pattern = ".nc")


radklim062023 <- terra::rast(listFiles06)
terra::crs(radklim062023) <- "+proj=stere +lat_0=90.0 +lon_0=10.0 +lat_ts=60.0 +a=6370040 +b=6370040 +units=m"
terra::ext(radklim062023) <- c(-443462,456538,-4758645,-3658645)

radklim082023 <- terra::rast(listFiles08)
terra::crs(radklim082023) <- "+proj=stere +lat_0=90.0 +lon_0=10.0 +lat_ts=60.0 +a=6370040 +b=6370040 +units=m"
terra::ext(radklim082023) <- c(-443462,456538,-4758645,-3658645)

# Gebiet zum zuschneiden
precipArea <- terra::vect("../../07_HECRAS/01_Daten/scalgo-live-LG_Bochum_boundary/dataset.shp")
terra::plot(precipArea)
terra::plet(precipArea)
precipAreaStere <- terra::project(precipArea, "+proj=stere +lat_0=90.0 +lon_0=10.0 +lat_ts=60.0 +a=6370040 +b=6370040 +units=m")
terra::plot(precipAreaStere)
terra::plet(precipAreaStere)

# Auf Zeitraum schneiden
# 06.2023
dateFilterStart062023 <- as.POSIXct("2023-06-22 00:00:00", tz = "UTC")
dateFilterEnd062023 <- as.POSIXct("2023-06-23 00:00:00", tz = "UTC")

radklim062023.time <- radklim062023[[terra::time(radklim062023) >= dateFilterStart062023 & terra::time(radklim062023) < dateFilterEnd062023]]

# 08.2023
dateFilterStart082023 <- as.POSIXct("2023-08-02 00:00:00", tz = "UTC")
dateFilterEnd082023 <- as.POSIXct("2023-08-09 00:00:00", tz = "UTC")

radklim082023.time <- radklim082023[[terra::time(radklim082023) >= dateFilterStart082023 & terra::time(radklim082023) <= dateFilterEnd082023]]

rm(radklim062023, radklim082023, precipArea, dateFilterEnd062023, dateFilterEnd082023, dateFilterStart062023, dateFilterStart082023)

# Auf Gebiet zuschneiden und max-values rausziehen
radklim062023.max <- terra::extract(radklim062023.time, precipAreaStere, fun=max, na.rm=TRUE, ID=FALSE)
radklim082023.max <- terra::extract(radklim082023.time, precipAreaStere, fun=max, na.rm=TRUE, ID=FALSE)

# zu dataframe schreiben
radklim062023.df <- data.table::melt(data.table::setDT(radklim062023.max), variable.name = "date") %>% as.data.frame()
radklim082023.df <- data.table::melt(data.table::setDT(radklim082023.max), variable.name = "date") %>% as.data.frame()

# Zeit ergänzen
radklim062023.df$date <- terra::time(radklim062023.time)
radklim082023.df$date <- terra::time(radklim082023.time)

ggplot(radklim062023.df, aes(x=date,y=value)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "5 hours",
                   date_labels = "%d.%m.%y %H:%M") +
  scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")
  
ggplot(radklim082023.df, aes(x=date,y=value)) + 
  geom_line(linewidth = 0.5, color = "black") + 
  scale_x_datetime(date_breaks = "1 day",
                   date_labels = "%d.%m.%y %H:%M") +
  scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")
```


```{r}
#Test ohne fun=max
radklim062023.fun <- terra::extract(radklim062023.time, precipAreaStere)
radklim062023.fun$ID <- seq(1,nrow(radklim062023.fun),1)

times <- terra::time(radklim062023.time)

radklim062023.fun_long <- radklim062023.fun %>% tidyr::pivot_longer(
  cols = starts_with("RR_"),
  names_to = "step",
  values_to = "RR"
) %>% 
  dplyr::mutate(
    step_num = as.integer(sub("RR_", "", step)),
    datum = times[step_num]
  )

radklim062023.fun_by_time <- radklim062023.fun_long %>% 
  dplyr::select(datum, ID, RR) %>% 
  tidyr::pivot_wider(
    names_from = ID,
    values_from = RR,
    names_prefix = "ID_"
  ) %>% 
  dplyr::arrange(datum)

radklim062023.fun_by_time_stats <- radklim062023.fun_by_time %>% dplyr::mutate(
  ID_mean = rowMeans(across(starts_with("ID_")), na.rm = TRUE),
  ID_max = do.call(pmax, c(across(starts_with("ID_")), list(na.rm = TRUE)))
)

radklim062023_summary <- radklim062023.fun_by_time_stats %>% 
  summarise(
    across(
      starts_with("ID_"),
      list(sum = ~ sum(.x, na.rm = TRUE))
    )
  )
```


# direkt Tagesdatei lesen
```{r}
radklim06Test <- terra::rast("../data/RADKLIM/untar/2023/06/YW_2017.002_20230622.nc")
terra::crs(radklim06Test) <- "+proj=stere +lat_0=90.0 +lon_0=10.0 +lat_ts=60.0 +a=6370040 +b=6370040 +units=m"
terra::ext(radklim06Test) <- c(-443462,456538,-4758645,-3658645)

precipArea <- terra::vect("../../07_HECRAS/01_Daten/scalgo-live-LG_Bochum_boundary/dataset.shp")
precipAreaStere <- terra::project(precipArea, "+proj=stere +lat_0=90.0 +lon_0=10.0 +lat_ts=60.0 +a=6370040 +b=6370040 +units=m")
precipAreaStere2 <- terra::project(precipArea, terra::crs(radklim06Test))

radklim06Test_extr1 <- terra::extract(radklim06Test, precipAreaStere, fun=max, na.rm=TRUE, ID=FALSE)
radklim06Test_extr2 <- terra::extract(radklim06Test, precipAreaStere2, fun=max, na.rm=TRUE, ID=FALSE)

radklim06Test_extr1.df <- data.table::melt(data.table::setDT(radklim06Test_extr1), variable.name = "date") %>% as.data.frame()
radklim06Test_extr2.df <- data.table::melt(data.table::setDT(radklim06Test_extr2), variable.name = "date") %>% as.data.frame()

radklim06Test_extr1.df$date <- terra::time(radklim06Test)
radklim06Test_extr2.df$date <- terra::time(radklim06Test)


# Umprojezieren RADKLIM auf EPSG
radklim06Test_porj <- terra::project(radklim06Test, terra::crs(precipArea))

radklim06Test_porj_extr <- terra::extract(radklim06Test_porj, precipArea, fun=max, na.rm=TRUE, ID=FALSE)
radklim06Test_porj_extr.df <- data.table::melt(data.table::setDT(radklim06Test_porj_extr), variable.name = "date") %>% as.data.frame()
radklim06Test_porj_extr.df$date <- terra::time(radklim06Test)


trusted <- radklim06Test_extr1.df
trusted_small <- trusted[order(trusted$date),]
write.csv(trusted_small, "../trusted_radklim_series.csv", row.names = FALSE)
```


# Plots
```{r}
# Radklim 06.2023
ggplot(radklim062023.df, aes(x=date,y=value)) + 
  geom_line(linewidth = 0.5, color = "black") +
  scale_x_datetime(date_breaks = "5 hours",
                   date_labels = "%d.%m.%y %H:%M") +
  scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/radklim_raw_062023.png", width = 15, height = 9, units = "cm", dpi = 1200)

# Radklim 08.2023
ggplot(radklim082023.df, aes(x=date,y=value)) + 
  geom_line(linewidth = 0.5, color = "black") +
  scale_x_datetime(date_breaks = "1 day",
                   date_labels = "%d.%m.%y") +
  scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]")

# ggsave("../plots/radklim_raw_082023.png", width = 15, height = 9, units = "cm", dpi = 1200)
```

# Funktion zum aggregieren
```{r}
library(dplyr)
library(lubridate)
library(zoo)  # für rollapply

aggregate_precip <- function(df, 
                             time_col = "time", 
                             value_col = "prec_mm",
                             target_intervals = c(5, 10, 15, 30, 60, 120, 360, 720, 1440),
                             na.rm = TRUE,
                             align_end = TRUE,
                             rolling = TRUE) {
  # --- 1️⃣ Zeitspalte prüfen ---
  if (!inherits(df[[time_col]], "POSIXt")) {
    stop("Die Zeitspalte muss vom Typ POSIXct oder POSIXlt sein.")
  }
  
  # --- 2️⃣ Zeitauflösung bestimmen ---
  dt <- median(diff(df[[time_col]]))
  dt_min <- as.numeric(dt, units = "mins")
  message(sprintf("Erkannte Zeitauflösung: %.2f Minuten", dt_min))
  
  # --- 3️⃣ nur Zielintervalle > Quellintervall ---
  valid_intervals <- target_intervals[target_intervals > dt_min + 1e-6]
  if (length(valid_intervals) == 0) {
    warning("Keine gültigen Zielintervalle größer als das Quellintervall gefunden.")
    return(NULL)
  }
  
  # --- 4️⃣ sortieren nach Zeit ---
  df <- df %>% arrange(.data[[time_col]])
  
  # --- 5️⃣ Aggregation ---
  results <- lapply(valid_intervals, function(int_min) {
    n <- round(int_min / dt_min)  # Anzahl Schritte im Aggregationsfenster
    
    if (rolling) {
      # 🔁 Gleitende Summenbildung
      roll_sum <- zoo::rollapply(df[[value_col]], width = n, FUN = sum, 
                                 align = "right", fill = NA, na.rm = na.rm)
      
      df_roll <- df %>%
        mutate(prec_sum = roll_sum,
               duration_min = int_min,
               interval_start = .data[[time_col]] - minutes(int_min),
               interval_end   = .data[[time_col]])
      
      if (align_end) {
        df_roll <- df_roll %>% mutate(interval = interval_end)
      } else {
        df_roll <- df_roll %>% mutate(interval = interval_start)
      }
      
      df_roll
    } else {
      # 📦 Blockweise Aggregation
      int_sec <- int_min * 60
      df_block <- df %>%
        mutate(interval_start = as.POSIXct(floor(as.numeric(.data[[time_col]]) / int_sec) * int_sec,
                                           origin = "1970-01-01", tz = tz(.data[[time_col]]))) %>%
        group_by(interval_start) %>%
        summarise(prec_sum = sum(.data[[value_col]], na.rm = na.rm), .groups = "drop") %>%
        mutate(duration_min = int_min,
               interval_end = interval_start + minutes(int_min),
               interval = if (align_end) interval_end else interval_start)
      df_block
    }
  })
  
  # --- 6️⃣ kombinieren ---
  out <- bind_rows(results)
  attr(out, "source_resolution_min") <- dt_min
  attr(out, "aggregated_intervals_min") <- valid_intervals
  attr(out, "aligned_to") <- if (align_end) "end" else "start"
  attr(out, "rolling") <- rolling
  return(out)
}
```

# Dauerstufen der Reihen erstellen
```{r}
# 06.2023
dsGelsenkirchen062023.rolling <- aggregate_precip(gelsenkirchen062023, time_col = "MESS_DATUM", value_col = "RS_05")
dsOlfen062023.rolling <- aggregate_precip(olfen062023, time_col = "MESS_DATUM", value_col = "RS_05")
dsWaltrop062023.rolling <- aggregate_precip(waltrop062023, time_col = "MESS_DATUM", value_col = "RS_05")
dsRadklim062023.rolling <- aggregate_precip(radklim062023.df, time_col = "date", value_col = "value")

dsGelsenkirchen062023 <- aggregate_precip(gelsenkirchen062023, time_col = "MESS_DATUM", value_col = "RS_05", rolling = FALSE)
dsOlfen062023 <- aggregate_precip(olfen062023, time_col = "MESS_DATUM", value_col = "RS_05", rolling = FALSE)
dsWaltrop062023 <- aggregate_precip(waltrop062023, time_col = "MESS_DATUM", value_col = "RS_05", rolling = FALSE)
dsRadklim062023 <- aggregate_precip(radklim062023.df, time_col = "date", value_col = "value", rolling = FALSE)

# 08.2023
dsGelsenkirchen082023.rolling <- aggregate_precip(gelsenkirchen082023, time_col = "MESS_DATUM", value_col = "RS_05")
dsOlfen082023.rolling <- aggregate_precip(olfen082023, time_col = "MESS_DATUM", value_col = "RS_05")
dsWaltrop082023.rolling <- aggregate_precip(waltrop082023, time_col = "MESS_DATUM", value_col = "RS_05")
dsRadklim082023.rolling <- aggregate_precip(radklim082023.df, time_col = "date", value_col = "value")

dsGelsenkirchen082023 <- aggregate_precip(gelsenkirchen082023, time_col = "MESS_DATUM", value_col = "RS_05", rolling = FALSE)
dsOlfen082023 <- aggregate_precip(olfen082023, time_col = "MESS_DATUM", value_col = "RS_05", rolling = FALSE)
dsWaltrop082023 <- aggregate_precip(waltrop082023, time_col = "MESS_DATUM", value_col = "RS_05", rolling = FALSE)
dsRadklim082023 <- aggregate_precip(radklim082023.df, time_col = "date", value_col = "value", rolling = FALSE)
```

# Dauerstufen plotten
```{r}
# 06.2023
ggplot(dsRadklim062023.rolling, aes(x=interval,y=prec_sum,color=as.factor(duration_min))) + 
  geom_line() +
  scale_x_datetime(date_breaks = "12 hours",
                   date_labels = "%d.%m.%y %H:%M") +
  # scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]",color="Dauerstufe [min]") 

# ggsave("../plots/radklim_dauerstufen_rolling_062023.png", width = 15, height = 9, units = "cm", dpi = 1200)

ggplot(dsRadklim062023, aes(x=interval,y=prec_sum,color=as.factor(duration_min))) + 
  geom_line() +
  scale_x_datetime(date_breaks = "12 hours",
                   date_labels = "%d.%m.%y %H:%M") +
  # scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]",color="Dauerstufe [min]") 

# ggsave("../plots/radklim_dauerstufen_062023.png", width = 15, height = 9, units = "cm", dpi = 1200)

# 08.2023
ggplot(dsRadklim082023.rolling, aes(x=interval,y=prec_sum,color=as.factor(duration_min))) + 
  geom_line() +
  scale_x_datetime(date_breaks = "1 days",
                   date_labels = "%d.%m.%y") +
  # scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]",color="Dauerstufe [min]") 

# ggsave("../plots/radklim_dauerstufen_rolling_082023.png", width = 15, height = 9, units = "cm", dpi = 1200)

ggplot(dsRadklim082023, aes(x=interval,y=prec_sum,color=as.factor(duration_min))) + 
  geom_line() +
  scale_x_datetime(date_breaks = "1 days",
                   date_labels = "%d.%m.%y") +
  # scale_y_continuous(breaks = seq(0,6,1)) +
  labs(x="Datum", y="Niederschlag [mm]",color="Dauerstufe [min]") 

# ggsave("../plots/radklim_dauerstufen_082023.png", width = 15, height = 9, units = "cm", dpi = 1200)
```

